# syntax=docker/dockerfile:1.7
FROM ubuntu:24.04

ARG PRODUCT
RUN groupadd --gid 10001 raksamp \
    && useradd --uid 10001 --gid 10001 --create-home --home-dir /work raksamp
WORKDIR /work
COPY --chown=10001:10001 . /work/
COPY --chmod=0755 raksamp /usr/local/bin/raksamp
RUN ln -s /usr/local/bin/raksamp "/usr/local/bin/raksamp-${PRODUCT}"
USER 10001:10001
EXPOSE 7777/udp
ENTRYPOINT ["raksamp"]
CMD ["--config", "/work/default-config.xml"]
